<?php

namespace App\Observers;

use App\Models\Language;
use App\Models\Translation;
use App\Models\TranslationKey;

class LanguageObserver
{
    public function created(Language $language)
    {
        // Varsayılan dil (İngilizce) için değerleri al
        $defaultValue = [
            'sidebar_main_menu' => 'Hauptmenü',
            'sidebar_home' => 'Startseite',
            'sidebar_users' => 'Benutzer',
            'sidebar_companys' => 'Firmen',
            'sidebar_roles' => 'Rollen',
            'sidebar_settings' => 'Einstellungen',
            'sidebar_languages' => 'Sprachen',
            'sidebar_software_settings' => 'Softwareeinstellungen',
            'sidebar_customers' => 'Kunden',
            'sidebar_employees' => 'Mitarbeiter',
            'sidebar_add_employees' => 'Mitarbeiter Hinzufügen',
            'sidebar_persons' => 'Personen',
            'sidebar_persons_customers' => 'Kunden',
            'sidebar_persons_carriers' => 'Träger',
            'sidebar_add_person' => 'Person Hinzufügen',
            'sidebar_shipments' => 'Sendungen',
            'sidebar_add_shipment' => 'Sendung Hinzufügen',
            'sidebar_support' => 'Unterstützung',
            'sidebar_invoices' => 'Rechnungen',
            'sidebar_payments' => 'Zahlungen',
            'sidebar_timocom' => 'TIMOCOM',

            'header_notifications' => 'Benachrichtigungen',
            'header_notifications_unread' => 'Ungelesene Benachrichtigungen',
            'header_fast_access' => 'Schnellzugriff',
            'header_profile' => 'Profil',
            'header_company_profile' => 'Profil',
            'header_logout' => 'Abmelden',
            'header_not_company' => 'Profil',
            'home_title' => 'Startseite',
            'home_name' => 'Startseite Name',
            'employees_table_page_title' => 'Mitarbeiter',
            'employees_table_name' => 'Mitarbeiter',
            'employees_table_home' => 'Startseite',
            'employees_table_add_employee' => 'Mitarbeiter Hinzufügen',
            'employees_table_name_surname' => 'Name Nachname',
            'employees_table_phone' => 'Telefon',
            'employees_table_company' => 'Firma',
            'employees_table_email' => 'E-Mail',
            'employees_table_class' => 'Klasse',
            'employees_table_status' => 'Status',
            'employees_table_status_active' => 'Aktiv',
            'employees_table_status_approve' => 'Genehmigen',
            'employees_table_detail' => 'Detail',
            'employees_table_conpany_not_found' => 'Firma Nicht Gefunden',
            'employees_table_detail_edit' => 'Bearbeiten',
            'employees_table_detail_delete' => 'Löschen',
            'employee_title' => 'Mitarbeiter',
            'employee_add_page_title' => 'Mitarbeiter Hinzufügen',
            'employee_add_name' => 'Mitarbeiter Anlegen',
            'employee_add_employees' => 'Mitarbeiter',
            'employee_add_form_name' => 'Name',
            'employee_add_form_surname' => 'Nachname',
            'employee_add_form_phone' => 'Telefon',
            'employee_add_form_email' => 'E-Mail',
            'employee_add_form_class' => 'Klasse',
            'employee_add_form_country' => 'Land',
            'employee_add_form_city' => 'Stadt',
            'employee_add_form_street' => 'Straße',
            'employee_add_form_zip_code' => 'Postleitzahl',
            'employee_add_form_address' => 'Adresse',
            'employee_add_form_password' => 'Passwort',
            'employee_add_form_password_confirm' => 'Passwort Bestätigen',
            'employee_add_form_create' => 'Erstellen',
            'employee_add_form_placeholder_name' => 'Name',
            'employee_add_form_placeholder_surname' => 'Nachname',
            'employee_add_form_placeholder_phone' => 'Telefon',
            'employee_add_form_placeholder_email' => 'E-Mail',
            'employee_add_form_placeholder_class' => 'Klasse',
            'employee_add_form_placeholder_country' => 'Land',
            'employee_add_form_placeholder_city' => 'Stadt',
            'employee_add_form_placeholder_street' => 'Straße',
            'employee_add_form_placeholder_zip_code' => 'Postleitzahl',
            'employee_add_form_placeholder_address' => 'Adresse',
            'employee_add_form_placeholder_password' => 'Passwort',
            'employee_add_form_placeholder_password_confirm' => 'Passwort Bestätigen',
            
            'employee_edit_page_title' => 'Mitarbeiter Bearbeiten',
            'employee_edit_name' => 'Name',
            'employee_edit_employees' => 'Mitarbeiter',
            'employee_edit_form_name' => 'Name',
            'employee_edit_form_surname' => 'Nachname',
            'employee_edit_form_phone' => 'Telefon',
            'employee_edit_form_email' => 'E-Mail',
            'employee_edit_form_class' => 'Klasse',
            'employee_edit_form_country' => 'Land',
            'employee_edit_form_city' => 'Stadt',
            'employee_edit_form_street' => 'Straße',
            'employee_edit_form_zip_code' => 'Postleitzahl',
            'employee_edit_form_edit' => 'Bearbeiten',
            'employee_edit_password_form_name' => 'Passwort',
            'employee_edit_password_form_password' => 'Passwort',
            'employee_edit_password_form_password_confirm' => 'Passwort Bestätigen',
            
            'employee_dashboard_page_title' => 'Personal Panel',
            'employee_dashboard_page_name' => 'Armaturenbrett',
            'employee_dashboard_card3_name' => 'Meine Rechnungen',
            'employee_dashboard_card3_more_info' => 'Mehr Informationen',
            'employee_dashboard_card4_name' => 'Meine Sendungen',
            'employee_dashboard_card4_more_info' => 'Mehr Informationen',
            'employee_dashboard_card5_name' => 'Mein Einkommen',
            'employee_dashboard_card5_more_info' => 'Mehr Informationen',
            
            'employee_dashboard_invoice' => 'Meine Rechnungen',
            'employee_dashboard_shipments' => 'Meine Sendungen',
            
            'employee_dashboard_invoice_date' => 'Geschichte',
            'employee_dashboard_invoice_price' => 'Preis',
            'employee_dashboard_invoice_detail' => 'Detail',
            
            'employee_dashboard_shipments_table_customer' => 'Kunde',
            'employee_dashboard_shipments_table_status' => 'Status',
            'employee_dashboard_shipments_table_price' => 'Gebühr',
            'employee_dashboard_shipments_table_type' => 'Typen',
            'employee_dashboard_shipments_table_detail' => 'Einzelheiten',
            
            
            'employee_edit_form_placeholder_name' => 'Name',
            'employee_edit_form_placeholder_surname' => 'Nachname',
            'employee_edit_form_placeholder_phone' => 'Telefon',
            'employee_edit_form_placeholder_email' => 'E-Mail',
            'employee_edit_form_placeholder_class' => 'Klasse',
            'employee_edit_form_placeholder_country' => 'Land',
            'employee_edit_form_placeholder_city' => 'Stadt',
            'employee_edit_form_placeholder_street' => 'Straße',
            'employee_edit_form_placeholder_zip_code' => 'Postleitzahl',
            'employee_edit_form_placeholder_address' => 'Adresse',
            'employee_edit_form_placeholder_edit' => 'Bearbeiten',
            'employee_edit_password_form_placeholder_name' => 'Passwort',
            'employee_edit_password_form_placeholder_password' => 'Passwort',
            'employee_edit_password_form_placeholder_password_confirm' => 'Passwort Bestätigen',
            
            'persons_customer_page_title' => 'Kontakte – Kunde',
            'persons_customer_page_name' => 'Kunden',
            'persons_customer_page_home' => 'Startseite',
            'persons_customer_person_add' => 'Person Hinzufügen',
            'persons_customer_table_name_surname' => 'Name',
            'persons_customer_table_phone' => 'Telefon',
            'persons_customer_table_company' => 'Firma',
            'persons_customer_table_email' => 'E-Mail',
            'persons_customer_table_person_type' => 'Personentyp',
            'persons_customer_table_person_type_customer' => 'Kunde',
            'persons_customer_table_detail' => 'Detail',
            'persons_customer_table_edit' => 'Bearbeiten',
            'persons_customer_table_delete' => 'Löschen',
            
            'persons_carrier_page_title' => 'Personen',
            'persons_carrier_page_name' => 'Name',
            'persons_carrier_page_home' => 'Startseite',
            'persons_carrier_person_add' => 'Person Hinzufügen',
            'persons_carrier_table_name' => 'Name',
            'persons_carrier_table_surname' => 'Nachname',
            'persons_carrier_table_phone' => 'Telefon',
            'persons_carrier_table_company' => 'Firma',
            'persons_carrier_table_email' => 'E-Mail',
            'persons_carrier_table_person_type' => 'Personentyp',
            'persons_carrier_table_person_type_carrier' => 'Träger',
            'persons_carrier_table_detail' => 'Detail',
            'persons_carrier_table_edit' => 'Bearbeiten',
            'persons_carrier_table_delete' => 'Löschen',
            
            'persons_add_page_title' => 'Person Hinzufügen',
            'persons_add_name' => 'Name',
            'persons_add_persons' => 'Personen',
            'persons_add_form_title' => 'Titel',
            'persons_add_form_name_surname' => 'Name Nachname',
            'persons_add_form_phone' => 'Telefon',
            'persons_add_form_company' => 'Firma',
            'persons_add_form_email' => 'E-Mail',
            'persons_add_form_person_type' => 'Personentyp',
            'persons_add_form_country' => 'Land',
            'persons_add_form_reverse_charge' => 'Reverse Charge',
            'persons_add_form_city' => 'Stadt',
            'persons_add_form_street' => 'Straße',
            'persons_add_form_zip_code' => 'Postleitzahl',
            'persons_add_form_address' => 'Adresse',
            'persons_add_form_person_type_customer' => 'Kunde',
            'persons_add_form_person_type_carrier' => 'Träger',
            'persons_add_form_placeholder_name_surname' => 'Name Nachname',
            'persons_add_form_placeholder_phone' => 'Telefon',
            'persons_add_form_placeholder_company' => 'Firma',
            'persons_add_form_placeholder_email' => 'E-Mail',
            'persons_add_form_placeholder_country' => 'Land',
            'persons_add_form_placeholder_city' => 'Stadt',
            'persons_add_form_placeholder_street' => 'Straße',
            'persons_add_form_placeholder_zip_code' => 'Postleitzahl',
            'persons_add_form_placeholder_address' => 'Adresse',
            'persons_add_form_create' => 'Erstellen',
            
            
            'persons_edit_page_title' => 'Person Hinzufügen',
            'persons_edit_name' => 'Name',
            'persons_edit_persons' => 'Personen',
            'persons_edit_form_title' => 'Titel',
            'persons_edit_form_name_surname' => 'Name Nachname',
            'persons_edit_form_phone' => 'Telefon',
            'persons_edit_form_company' => 'Firma',
            'persons_edit_form_email' => 'E-Mail',
            'persons_edit_form_person_type' => 'Personentyp',
            'persons_edit_form_country' => 'Land',
            'persons_edit_form_reverse_charge' => 'Reverse Charge',
            'persons_edit_form_city' => 'Stadt',
            'persons_edit_form_street' => 'Straße',
            'persons_edit_form_zip_code' => 'Postleitzahl',
            'persons_edit_form_address' => 'Adresse',
            'persons_edit_form_person_type_customer' => 'Kunde',
            'persons_edit_form_person_type_carrier' => 'Träger',
            'persons_edit_form_placeholder_name_surname' => 'Name Nachname',
            'persons_edit_form_placeholder_phone' => 'Telefon',
            'persons_edit_form_placeholder_company' => 'Firma',
            'persons_edit_form_placeholder_email' => 'E-Mail',
            'persons_edit_form_placeholder_country' => 'Land',
            'persons_edit_form_placeholder_city' => 'Stadt',
            'persons_edit_form_placeholder_street' => 'Straße',
            'persons_edit_form_placeholder_zip_code' => 'Postleitzahl',
            'persons_edit_form_placeholder_address' => 'Adresse',
            'persons_edit_form_create' => 'Erstellen',
            
            
            
            'login_page_title' => 'Anmeldung',
            'login_name' => 'Anmeldung',
            'login_sub_name' => 'Willkommen zurück',
            'login_form_email' => 'Email',
            'login_form_password' => 'Passwort',
            'login_form_remember_me' => 'Erinnere dich an mich',
            'login_form_reset_password' => 'Passwort vergessen ?',
            'login_form_placeholder_email' => 'Email',
            'login_form_placeholder_password' => 'Passwort',
            'login_form_login' => 'Anmeldung',
            'login_dont_have_an_account_yet' => 'Sie haben noch kein Konto?',
            'login_create_account' => 'Benutzerkonto erstellen',
            
            'register_page_title' => 'Registrieren',
            'register_company_register' => 'Firmen Registrierung',
            'register_person_register' => 'Personal Registrierung',
            'register_company_page_name' => 'Erstellen Sie eine Firmenregistrierung',
            'register_company_page_sub_name' => 'Geben Sie Ihre Firmeninformationen ein',
            'register_company_form_company_name' => 'Name der Firma:',
            'register_company_form_company_phone' => 'Telefongesellschaft:',
            'register_company_form_company_email' => 'Firmen-E-Mail:',
            'register_company_form_company_tax' => 'Unternehmenssteuernummer:',
            'register_company_form_company_street' => 'Firmen Straße:',
            'register_company_form_company_zip_code' => 'Postleitzahl:',
            'register_company_form_company_city' => 'Firmenprovinz:',
            'register_company_form_company_country' => 'Firmenland:',
            'register_company_form_company_placeholder_name' => 'Name der Firma',
            'register_company_form_company_placeholder_phone' => 'Telefongesellschaft',
            'register_company_form_company_placeholder_email' => 'Firmen-E-Mail',
            'register_company_form_company_placeholder_tax' => 'Unternehmenssteuernummer',
            'register_company_form_company_placeholder_street' => 'Firmen Straße',
            'register_company_form_company_placeholder_zip_code' => 'Postleitzahl',
            'register_company_form_company_placeholder_city' => 'Firmenprovinz',
            'register_company_form_company_placeholder_country' => 'Firmenland',
            
            'register_company_admin_title' => 'Geben Sie Ihre autorisierten Informationen ein',
            'register_company_form_admin_name' => 'Autorisierter Name:',
            'register_company_form_admin_surname' => 'Autorisierter Nachname:',
            'register_company_form_admin_email' => 'Autorisierte E-Mail:',
            'register_company_form_admin_phone' => 'Autorisierte Telefonnummer:',
            'register_company_form_admin_street' => 'Straße:',
            'register_company_form_admin_zip_code' => 'Postleitzahl:',
            'register_company_form_admin_city' => 'Provinz:',
            'register_company_form_admin_country' => 'Land:',
            'register_company_form_admin_placeholder_name' => 'Autorisierter Name',
            'register_company_form_admin_placeholder_surname' => 'Autorisierter Nachname',
            'register_company_form_admin_placeholder_email' => 'Autorisierte E-Mail',
            'register_company_form_admin_placeholder_phone' => 'Autorisierte Telefonnummer',
            'register_company_form_admin_placeholder_street' => 'Straße',
            'register_company_form_admin_placeholder_zip_code' => 'Postleitzahl',
            'register_company_form_admin_placeholder_city' => 'Provinz',
            'register_company_form_admin_placeholder_country' => 'Land',
            
            'register_company_form_password' => 'Passwort:',
            'register_company_form_password_confirm' => 'Bestätige das Passwort:',
            'register_company_form_placeholder_password' => 'Passwort',
            'register_company_form_placeholder_password_confirm' => 'Bestätige das Passwort',
            'register_company_form_register' => 'Registrieren',
            
            
            
            'register_person_page_name' => 'Personalakte erstellen:',
            'register_person_page_sub_name' => 'Geben Sie Ihre Daten ein',
            
            'register_person_form_name' => 'Name:',
            'register_person_form_surname' => 'Nachname:',
            'register_person_form_phone' => 'Email:',
            'register_person_form_email' => 'Telefon:',
            'register_person_form_reference_code' => 'Firmenreferenzcode:',
            'register_person_form_placeholder_name' => 'Name',
            'register_person_form_placeholder_surname' => 'Nachname',
            'register_person_form_placeholder_phone' => 'Email',
            'register_person_form_placeholder_email' => 'Telefon',
            'register_person_form_placeholder_reference_code' => 'Firmenreferenzcode',
            
            'register_person_form_password' => 'Passwort:',
            'register_person_form_password_confirm' => 'Bestätige das Passwort:',
            'register_person_form_placeholder_password' => 'Passwort',
            'register_person_form_placeholder_password_confirm' => 'Bestätige das Passwort',
            'register_person_form_register' => 'Registrieren',
            
            'register_form_do_you_have_an_account' => 'Hast du einen Account ?',
            'register_form_do_you_have_an_account_login' => 'Anmeldung',
            
            'approve_page_title' => 'Genehmigungsphase',
            'approve_company_title' => 'Ihre Angaben werden innerhalb von maximal 2 Tagen überprüft.',
            'approve_company_message' => 'Ihr Unternehmen und das Administratorkonto Ihres Unternehmens werden überprüft. Die Überprüfung dauert maximal 2 Tage. Bitte verwenden Sie die persönliche E-Mail-Adresse, die Sie bei der Registrierung verwendet haben:',
            'approve_company_message_2' => 'Überprüfen Sie Ihr Kontrollkästchen.',
            'approve_person_title' => 'Ihre Angaben werden innerhalb von maximal 2 Tagen überprüft.',
            'approve_person_message' => 'Da Sie sich mit der Firmenreferenznummer registriert haben, warten Sie auf die Genehmigung des Firmenleiters. Bitte wenden Sie sich an Ihren Firmenadministrator.',
            'approve_logout' => 'Ausloggen',
            
            'password_reset_email_page_title' => 'Anfrage zum Zurücksetzen des Passworts',
            'password_reset_email_title' => 'Passwort zurücksetzen',
            'password_reset_email_sub_title' => 'Senden Sie eine Anfrage zum Zurücksetzen des Passworts',
            'password_reset_email_form_email' => 'Ihre im System registrierte E-Mail-Adresse:',
            'password_reset_email_form_placeholder_email' => 'E-Mail',
            'password_reset_email_form_reset' => 'Senden Sie eine Reset-Anfrage',
            'password_reset_email_do_you_know_your_password' => 'Kennen Sie Ihr Passwort?',
            'password_reset_email_do_you_know_your_password_login' => 'Anmeldung',
            
            'password_reset_page_title' => 'Setze dein Passwort zurück',
            'password_reset_title' => 'Passwort zurücksetzen',
            'password_reset_sub_title' => 'Willkommen zurück',
            'password_reset_form_password' => 'Passwort:',
            'password_reset_form_password_confirm' => 'Bestätige das Passwort:',
            'password_reset_form_placeholder_password' => 'Passwort',
            'password_reset_form_placeholder_password_confirm' => 'Bestätige das Passwort',
            'password_reset_form_reset' => 'Zurücksetzen',
            
            'edit_profile_page_title' => 'Profil Bearbeiten',
            'edit_profile_page_name' => 'Profil Bearbeiten',
            
            'edit_profile_sidebar_info' => 'Persönliche Angaben',
            'edit_profile_sidebar_address' => 'Adresse',
            'edit_profile_sidebar_security' => 'Sizherheit',
            'edit_profile_header_email' => 'E-Mail:',
            'edit_profile_header_phone' => 'Telefon:',
            
            'edit_profile_info_title' => 'Profil bearbeiten:',
            'edit_profile_info_form_name' => 'Name:',
            'edit_profile_info_form_surname' => 'Nachname:',
            'edit_profile_info_form_phone' => 'Telefon:',
            'edit_profile_info_form_email' => 'E-Mail-Adresse :',
            'edit_profile_info_form_placeholder_name' => 'Name',
            'edit_profile_info_form_placeholder_surname' => 'Nachname',
            'edit_profile_info_form_placeholder_phone' => 'Telefon',
            'edit_profile_info_form_placeholder_email' => 'E-Mail-Adresse',
            'edit_profile_info_form_save' => 'Aktualisieren',
            
            'edit_profile_address_title' => 'Adresse aktualisieren:',
            'edit_profile_address_form_street' => 'Straße:',
            'edit_profile_address_form_zip_code' => 'Postleitzahl:',
            'edit_profile_address_form_city' => 'Der:',
            'edit_profile_address_form_country' => 'Land:',
            'edit_profile_address_form_placeholder_street' => 'Straße',
            'edit_profile_address_form_placeholder_zip_code' => 'Postleitzahl',
            'edit_profile_address_form_placeholder_city' => 'Der',
            'edit_profile_address_form_placeholder_country' => 'Land',
            'edit_profile_address_form_save' => 'Aktualisieren',
            
            'edit_profile_security_title' => 'Kennwort aktualisieren:',
            'edit_profile_security_form_current_password' => 'Aktuelles Passwort :',
            'edit_profile_security_form_new_password' => 'Neues Kennwort :',
            'edit_profile_security_form_new_password_confirm' => 'Neues Passwort bestätigen:',
            'edit_profile_security_form_placeholder_current_password' => 'Aktuelles Passwort',
            'edit_profile_security_form_placeholder_new_password' => 'Neues Kennwort',
            'edit_profile_security_form_placeholder_new_password_confirm' => 'Neues Passwort bestätigen',
            'edit_profile_security_form_save' => 'Aktualisieren',
            
            'company_dashboard_page_title' => 'Unternehmensleitungsgremium',
            'company_dashboard_page_name' => 'Armaturenbrett',
            'company_dashboard_card1_name' => 'Personen',
            'company_dashboard_card1_more_info' => 'Mehr Informationen',
            'company_dashboard_card2_name' => 'Mitarbeiter',
            'company_dashboard_card2_more_info' => 'Mehr Informationen',
            'company_dashboard_card3_name' => 'Rechnungen',
            'company_dashboard_card3_more_info' => 'Mehr Informationen',
            'company_dashboard_card4_name' => 'Sendungen',
            'company_dashboard_card4_more_info' => 'Mehr Informationen',
            'company_dashboard_card5_name' => 'Verdienen',
            'company_dashboard_card5_more_info' => 'Mehr Informationen',
            
            'company_dashboard_movements' => 'Kürzliche Transaktionen',
            'company_dashboard_personnel_earnings_table' => 'Personalverdiensttabelle',
            'company_dashboard_company_earnings_statistics' => 'Statistik Der Unternehmensgewinne',
            'company_dashboard_shipments' => 'Sendungen',
            
            'company_dashboard_personnel_earnings_table_name_surname' => 'Name Nachname',
            'company_dashboard_personnel_earnings_table_earning' => 'Verdienen',
            'company_dashboard_personnel_earnings_table_ratio' => 'Oran',
            
            'company_dashboard_shipments_table_customer' => 'Kunde',
            'company_dashboard_shipments_table_status' => 'Status',
            'company_dashboard_shipments_table_price' => 'Gebühr',
            'company_dashboard_shipments_table_type' => 'Typen',
            'company_dashboard_shipments_table_detail' => 'Einzelheiten',
            
            // Company Edit Start
            'company_profile_edit_name' => 'Unternehmensprofil',
            'company_profile_edit_page_title' => 'Einzelheiten',
            
            'company_profile_edit_tab_company_info' => 'Firmeninformation',
            'company_profile_edit_company_info_name' => 'Firmenprofil bearbeiten:',
            'company_profile_edit_company_info_phone' => 'Telefon',
            'company_profile_edit_company_info_email' => 'E-Mail',
            'company_profile_edit_company_info_profile_image_save' => 'Profilbild speichern',
            
            'company_profile_edit_company_info_form_company_name' => 'Name der Firma:',
            'company_profile_edit_company_info_form_tax_number' => 'Unternehmenssteuernummer:',
            'company_profile_edit_company_info_form_phone' => 'Telefongesellschaft:',
            'company_profile_edit_company_info_form_email' => 'Firmen-E-Mail:',
            'company_profile_edit_company_info_form_fax' => 'Faks:',
            'company_profile_edit_company_info_form_hrb' => 'HRB:',
            'company_profile_edit_company_info_form_iban' => 'Iban:',
            'company_profile_edit_company_info_form_bic' => 'Bic:',
            'company_profile_edit_company_info_form_stnr' => 'StNr:',
            'company_profile_edit_company_info_form_ustidnr' => 'Ust-Id Nr.:',
            'company_profile_edit_company_info_form_registry_court' => 'Registergericht:',
            'company_profile_edit_company_info_form_general_manager' => 'Geschäftsführer:',
            'company_profile_edit_company_info_form_logo' => 'Firmenlogo:',
            'company_profile_edit_company_info_form_save' => 'Aktualisieren',
            
            'company_profile_edit_company_info_form_placeholder_company_name' => 'Name der Firma',
            'company_profile_edit_company_info_form_placeholder_tax_number' => 'Unternehmenssteuernummer',
            'company_profile_edit_company_info_form_placeholder_phone' => 'Telefongesellschaft',
            'company_profile_edit_company_info_form_placeholder_email' => 'Firmen-E-Mail',
            'company_profile_edit_company_info_form_placeholder_fax' => 'Faks',
            'company_profile_edit_company_info_form_placeholder_hrb' => 'HRB',
            'company_profile_edit_company_info_form_placeholder_iban' => 'Iban',
            'company_profile_edit_company_info_form_placeholder_bic' => 'Bic',
            'company_profile_edit_company_info_form_placeholder_stnr' => 'StNr',
            'company_profile_edit_company_info_form_placeholder_ustidnr' => 'Ust-Id Nr.',
            'company_profile_edit_company_info_form_placeholder_registry_court' => 'Registergericht',
            'company_profile_edit_company_info_form_placeholder_general_manager' => 'Geschäftsführer',
            
            'company_profile_edit_tab_company_address' => 'Adresse',
            'company_profile_edit_company_address_name' => 'Firmenadresse :',
            
            'company_profile_edit_company_address_form_street' => 'Straße:',
            'company_profile_edit_company_address_form_zip_code' => 'Postleitzahl:',
            'company_profile_edit_company_address_form_city' => 'Stadt:',
            'company_profile_edit_company_address_form_country' => 'Land:',
            'company_profile_edit_company_address_form_save' => 'Aktualisieren',
            
            'company_profile_edit_company_address_form_placeholder_street' => 'Straße',
            'company_profile_edit_company_address_form_placeholder_zip_code' => 'Postleitzahl',
            'company_profile_edit_company_address_form_placeholder_city' => 'Stadt',
            'company_profile_edit_company_address_form_placeholder_country_no' => 'nicht ausgewählt',
            // Company Edit End
            
            // Company Profile Start
            'company_profile_name' => 'Firmenprofil',
            'company_profile_page_title' => 'Firmenprofil',
            'company_profile_reference_no' => 'Referenznummer:',
            'company_profile_shipments' => 'Sendung',
            'company_profile_workers' => 'Arbeiter',
            'company_profile_invoices' => 'Rechnung',
            'company_profile_edit_button' => 'Bearbeiten',
            
            'company_profile_sidebar_name' => 'Firmeninformation :',
            'company_profile_sidebar_company_name' => 'Name der Firma :',
            'company_profile_sidebar_email' => 'E-Mail :',
            'company_profile_sidebar_fax' => 'Fax :',
            'company_profile_sidebar_hrb' => 'HRB :',
            'company_profile_sidebar_iban' => 'Iban :',
            'company_profile_sidebar_bic' => 'Bic :',
            'company_profile_sidebar_stnr' => 'StNr :',
            'company_profile_sidebar_ustidnr' => 'Ust-Id Nr. :',
            'company_profile_sidebar_registry_court' => 'Registergericht :',
            'company_profile_sidebar_general_manager' => 'Hauptgeschäftsführer :',
            'company_profile_sidebar_phone' => 'Telefon :',
            'company_profile_sidebar_workers' => 'Arbeiter :',
            'company_profile_sidebar_contact_name' => 'Kontaktinformationen :',
            
            'company_profile_tab_workers' => 'Arbeiter',
            'company_profile_tab_workers_search' => 'Suchen',
            'company_profile_tab_workers_modal_header' => ' - Detail',
            'company_profile_tab_workers_modal_company_name' => 'Name der Firma:',
            'company_profile_tab_workers_modal_email' => 'E-Mail:',
            'company_profile_tab_workers_modal_role' => 'Titel:',
            'company_profile_tab_workers_modal_created' => 'Erstellungsdatum:',
            'company_profile_tab_workers_modal_edit_button' => 'Bearbeiten',
            'company_profile_tab_workers_modal_review_button' => 'Rezension:',

            'company_profile_tab_customers' => 'Kunden',
            'company_profile_tab_customers_search' => 'Suchen',
            'company_profile_tab_customer_select_email' => 'Mail senden',
            'company_profile_tab_customer_select_phone' => 'Rufen Sie das Telefon an',
            'company_profile_tab_customer_select_edit' => 'Bearbeiten',
            'company_profile_tab_customer_select_view' => 'Sicht',
            'company_profile_tab_customer_select_delete' => 'Löschen',
            'company_profile_tab_customer_modal_name' => '- Detail',
            'company_profile_tab_customer_modal_company_name' => 'Name der Firma:',
            'company_profile_tab_customer_modal_company_no_company' => 'keine Firma',
            'company_profile_tab_customer_modal_company_phone' => 'Telefon:',
            'company_profile_tab_customer_modal_company_email' => 'E-Mail:',
            'company_profile_tab_customer_modal_company_reverse_charge' => 'Umgekehrte Änderung:',
            'company_profile_tab_customer_modal_company_active' => 'Aktiv',
            'company_profile_tab_customer_modal_company_passive' => 'Pasiv',
            'company_profile_tab_customer_modal_company_edit' => 'Bearbeiten',
            'company_profile_tab_customer_modal_company_exit' => 'Schließen',

            'company_profile_tab_carriers' => 'Versender',
            'company_profile_tab_carriers_search' => 'Suchen',
            'company_profile_tab_carrier_select_email' => 'Mail senden',
            'company_profile_tab_carrier_select_phone' => 'Rufen Sie das Telefon an',
            'company_profile_tab_carrier_select_edit' => 'Bearbeiten',
            'company_profile_tab_carrier_select_view' => 'Sicht',
            'company_profile_tab_carrier_select_delete' => 'Löschen',
            'company_profile_tab_carrier_modal_name' => '- Detail',
            'company_profile_tab_carrier_modal_company_name' => 'Name der Firma:',
            'company_profile_tab_carrier_modal_company_no_company' => 'keine Firma',
            'company_profile_tab_carrier_modal_company_phone' => 'Telefon:',
            'company_profile_tab_carrier_modal_company_email' => 'E-Mail:',
            'company_profile_tab_carrier_modal_company_edit' => 'Bearbeiten',
            'company_profile_tab_carrier_modal_company_exit' => 'Schließen',
            
            'company_profile_tab_shipments' => 'Sendungen',
            'company_profile_tab_shipments_table_name' => 'Sendungen',
            'company_profile_tab_shipments_table_shipment_no' => 'Versand Nr.',
            'company_profile_tab_shipments_table_customer' => 'Kunde',
            'company_profile_tab_shipments_table_author' => 'Bestandteil',
            'company_profile_tab_shipments_table_status' => 'Situation',
            'company_profile_tab_shipments_table_status_cancel' => 'Es wird abgesagt',
            'company_profile_tab_shipments_table_status_draft' => 'Entwurf',
            'company_profile_tab_shipments_table_status_continues' => 'Unterwegs',
            'company_profile_tab_shipments_table_status_approved' => 'Genehmigt',
            'company_profile_tab_shipments_table_status_not' => 'Unbekannte Situation',
            'company_profile_tab_shipments_table_created_time' => 'Erstellungsdatum',
            'company_profile_tab_shipments_table_updated_time' => 'Aktualisiert',
            'company_profile_tab_shipments_table_amount' => 'Gebühr',
            'company_profile_tab_shipments_table_details' => 'Transaktionen',
            // Company Profile End
            
            // Invoices Start
            'company_invoices_name' => 'Rechnungen',
            'company_invoices_sub_name' => 'Sendungen',
            'company_invoices_page_title' => 'Rechnungen',
            
            'company_invoices_cart_1' => 'Gesamtmonatsumsatz',
            'company_invoices_cart_2' => 'MwSt. insgesamt',
            'company_invoices_cart_3' => 'Kunde aus Übersee',
            'company_invoices_cart_4' => 'Wöchentlicher Rechnungen',
            
            'company_invoices_table_name' => 'Rechnungen',
            'company_invoices_table_invoice_id' => 'Rechnung-ID',
            'company_invoices_table_author' => 'Bestandteil',
            'company_invoices_table_amount' => 'Menge',
            'company_invoices_table_amount_vat' => 'MwSt:',
            'company_invoices_table_created_time' => 'Erstellungsdatum',
            'company_invoices_table_updated_time' => 'Datum der Ausstellung',
            'company_invoices_table_details' => 'Transaktionen',
            
            'company_invoices_table_modal_header_invoice_no_text' => 'Nummerierte Versandinformationen',
            'company_invoices_table_modal_header_invoice_no_name' => 'Rechnungs Nummer :',
            'company_invoices_table_modal_header_invoice_download' => 'Rechnung Herunterladen',
            
            'company_invoices_table_modal_customer' => 'Kunden',
            'company_invoices_table_modal_customer_reverse_label' => 'Umgekehrte Änderung:',
            'company_invoices_table_modal_customer_reverse_active' => 'Aktiv',
            'company_invoices_table_modal_customer_reverse_passive' => 'Pasif',
            
            'company_invoices_table_modal_company' => 'Firma :',
            'company_invoices_table_modal_company_fax' => 'Fax :',
            'company_invoices_table_modal_company_hrb' => 'HRB :',
            'company_invoices_table_modal_company_iban' => 'IBAN :',
            'company_invoices_table_modal_company_bic' => 'Bic :',
            'company_invoices_table_modal_company_stnr' => 'StNr :',
            'company_invoices_table_modal_company_ustidnr' => 'Ust Id Nr:',
            'company_invoices_table_modal_company_registry_court' => 'Registergericht',
            'company_invoices_table_modal_company_invoice_no' => 'Versand-ID :',
            'company_invoices_table_modal_company_created_time' => 'Erstellungsdatum :',
            'company_invoices_table_modal_company_updated_time' => 'Bearbeitungsdatum :',
            'company_invoices_table_modal_company_amount' => 'Versandbetrag :',
            
            'company_invoices_table_modal_carrier' => 'Transporter :',

            'company_invoices_table_modal_upload_info_title' => 'Adresse Hochladen :',
            'company_invoices_table_modal_upload_info_company' => 'Firma',
            'company_invoices_table_modal_upload_info_name' => 'Name',
            'company_invoices_table_modal_upload_info_phone' => 'Telefon',
            'company_invoices_table_modal_upload_info_reference' => 'Referenz',
            'company_invoices_table_modal_upload_info_time' => 'Verladedatum',
            'company_invoices_table_modal_upload_info_time_period' => 'Zeitfenster',
            'company_invoices_table_modal_upload_info_address' => 'Adresse',
            'company_invoices_table_modal_upload_info_details' => 'Details',
            
            'company_invoices_table_modal_delivery_info_title' => 'Liefer Adresse :',
            'company_invoices_table_modal_delivery_info_company' => 'Firma',
            'company_invoices_table_modal_delivery_info_name' => 'Name',
            'company_invoices_table_modal_delivery_info_reference' => 'Referenz',
            'company_invoices_table_modal_delivery_info_time' => 'Verladedatum',
            'company_invoices_table_modal_delivery_info_time_period' => 'Zeitfenster',
            'company_invoices_table_modal_delivery_info_address' => 'Adresse',
            'company_invoices_table_modal_delivery_info_details' => 'Details',
            
            'company_invoices_table_modal_footer_title' => 'Betrags Informationen :',
            'company_invoices_table_modal_footer_amount' => 'Menge :',
            'company_invoices_table_modal_footer_carrier_amount' => 'Versandkosten :',
            'company_invoices_table_modal_footer_vat' => 'MwSt :',
            'company_invoices_table_modal_footer_total_amount' => 'Einzelheiten',
            // Invoices End
            
            // shipments Start
            'company_shipments_page_title' => 'Sendungen',
            'company_shipments_name' => 'Sendungen',
            'company_shipments_sub_name' => 'Home',
            'company_shipments_cart_1' => 'Gesamtmonatsumsatz',
            'company_shipments_cart_2' => 'Monatliche Versandkosten',
            'company_shipments_cart_3' => 'Monatliches Nettoeinkommen',
            'company_shipments_cart_4' => 'Wöchentlicher Versand',
            'company_shipments_table_name' => 'Sendungen',
            'company_shipments_table_add_shipment_button' => 'Sendun Erstellen',
            'company_shipments_table_shipment_no' => 'Versand-ID',
            'company_shipments_table_customer' => 'Kunde',
            'company_shipments_table_author' => 'Erstellt von',
            'company_shipments_table_carrier' => 'Spediteur',
            'company_shipments_table_carrier_no' => 'Nein',
            'company_shipments_table_carrier_yes' => 'Es gibt',
            'company_shipments_table_amount' => 'Kosten',
            'company_shipments_table_amount_vat' => 'MwSt:',
            'company_shipments_table_gain' => 'Gewinn',
            'company_shipments_table_status' => 'Status',
            'company_shipments_table_span_1_cancel' => 'Storniert',
            'company_shipments_table_span_2_draft' => 'Entwurf',
            'company_shipments_table_span_3_continues' => 'geht weiter',
            'company_shipments_table_span_4_approved' => 'genehmigt',
            'company_shipments_table_span_5_not' => 'genehmigt',
            'company_shipments_table_details' => 'Details',
            'company_shipments_table_details_edit' => 'bearbeiten',
            'company_shipments_table_details_del' => 'löschen',
            'company_shipments_table_details_view' => 'Sicht',
            
            'company_shipments_table_modal_header_shipment_no_text' => 'Nummerierte Versandinformationen',
            'company_shipments_table_modal_header_shipment_no_name' => 'Lieferungs Nummer :',
            'company_shipments_table_modal_header_button_1_cancel' => 'Storniert',
            'company_shipments_table_modal_header_button_2_approve' => 'Versand Bestätigen',
            'company_shipments_table_modal_header_button_3_pdf_download' => 'PDF Herunterladen',
            'company_shipments_table_modal_header_button_4_shipment_finish' => 'Versand beenden',
            'company_shipments_table_modal_header_button_5_add_invoice' => 'Rechnung erstellen',
            'company_shipments_table_modal_header_button_6_invoice_download' => 'Download Rechnung',
            
            'company_shipments_table_modal_invoice_form_name' => 'Rechnung Erstellen:',
            'company_shipments_table_modal_invoice_form_amount' => 'Preis',
            'company_shipments_table_modal_invoice_form_date' => 'Geschichte',
            'company_shipments_table_modal_invoice_form_add_button' => 'Rechnung Erstellen',
            
            'company_shipments_table_modal_header_span_1_cancel' => 'Storniert',
            'company_shipments_table_modal_header_span_2_draft' => 'Entwurf',
            'company_shipments_table_modal_header_span_3_continues' => 'geht weiter',
            'company_shipments_table_modal_header_span_4_approved' => 'Genehmigt',
            'company_shipments_table_modal_header_span_5_not' => 'nein',
            
            'company_shipments_table_modal_customer' => 'Kunde :',
            'company_shipments_table_modal_reverse_charge' => 'Reverse Charge',
            'company_shipments_table_modal_reverse_charge_active' => 'aktiv',
            'company_shipments_table_modal_reverse_charge_passive' => 'passiv',
            
            'company_shipments_table_modal_carrier' => 'Transporter :',


            'company_shipments_table_modal_company' => 'Firma :',
            'company_shipments_table_modal_fax' => 'Fax:',
            'company_shipments_table_modal_iban' => 'Iban:',
            'company_shipments_table_modal_hrb' => 'HRB:',
            'company_shipments_table_modal_bic' => 'Bic:',
            'company_shipments_table_modal_stnr' => 'StNr:',
            'company_shipments_table_modal_ustidnr' => 'Ust Id Nr:',
            'company_shipments_table_modal_registry_court' => 'Registergericht',
            
            'company_shipments_table_modal_shipment_no' => 'Versand-ID :',
            'company_shipments_table_modal_created_time' => 'Erstellungsdatum :',
            'company_shipments_table_modal_created_updated' => 'Bearbeitungsdatum :',
            'company_shipments_table_modal_amount' => 'Versandbetrag :',
            
            'company_shipments_table_modal_upload_table_title' => 'Adresse Hochladen :',
            'company_shipments_table_modal_upload_table_company' => 'Firma :',
            'company_shipments_table_modal_upload_table_name' => 'Name :',
            'company_shipments_table_modal_upload_table_phone' => 'Telefon :',
            'company_shipments_table_modal_upload_table_reference' => 'Referenz',
            'company_shipments_table_modal_upload_table_upload_date' => 'Verladedatum',
            'company_shipments_table_modal_upload_table_time_range' => 'Zeitfenster',
            'company_shipments_table_modal_upload_table_address' => 'Adresse',
            'company_shipments_table_modal_upload_table_details' => 'Details',
            
            'company_shipments_table_modal_delivery_table_title' => 'Liefer Adresse :',
            'company_shipments_table_modal_delivery_table_company' => 'Firma :',
            'company_shipments_table_modal_delivery_table_name' => 'Name :',
            'company_shipments_table_modal_delivery_table_phone' => 'Telefon :',
            'company_shipments_table_modal_delivery_table_reference' => 'Referenz',
            'company_shipments_table_modal_delivery_table_upload_date' => 'Verladedatum',
            'company_shipments_table_modal_delivery_table_time_range' => 'Zeitfenster',
            'company_shipments_table_modal_delivery_table_address' => 'Adresse',
            'company_shipments_table_modal_delivery_table_details' => 'Details',
            
            'company_shipments_table_modal_amount_table_name' => 'Betrags Informationen :',
            'company_shipments_table_modal_amount_table_vat' => 'MwSt :',
            'company_shipments_table_modal_amount_table_amount' => 'Gesamtmenge :',
            'company_shipments_table_modal_amount_table_carrier_price' => 'Versandkosten :',
            'company_shipments_table_modal_amount_table_total_amount' => 'Gesamteinnahmen :',
            // Shipments End
            
            // Shipments Add Start
            'company_shipments_add_name' => 'Sendung Erstellen',
            'company_shipments_add_sub_name' => 'Sendungen',
            'company_shipments_add_page_title' => 'Sendung Erstellen',
            
            'company_shipments_add_form_customer_title' => 'Kunden Information :',
            'company_shipments_add_form_customer_new_select' => 'new',
            'company_shipments_add_form_customer_company_name' => 'Name der Firma',
            'company_shipments_add_form_customer_name_and_surname' => 'Vorname Familienname',
            'company_shipments_add_form_customer_street' => 'Straße',
            'company_shipments_add_form_customer_zip_code' => 'Postleitzahl',
            'company_shipments_add_form_customer_city' => 'Stadt',
            'company_shipments_add_form_customer_email' => 'Kunden E-Mail',
            'company_shipments_add_form_customer_phone' => 'Kunden Telefon',
            'company_shipments_add_form_customer_reverse_charge' => ' Reverse Charge',
            
            'company_shipments_add_form_carrier_check' => 'Ich werde den Transport nicht selbst durchführen',
            'company_shipments_add_form_carrier_title' => 'Transporter:',
            'company_shipments_add_form_carrier_new_select' => 'new',
            'company_shipments_add_form_carrier_company_name' => 'Name der Firma',
            'company_shipments_add_form_carrier_name_and_surname' => 'Vorname Familienname',
            'company_shipments_add_form_carrier_street' => 'Straße',
            'company_shipments_add_form_carrier_zip_code' => 'Postleitzahl',
            'company_shipments_add_form_carrier_city' => 'Stadt',
            'company_shipments_add_form_carrier_email' => 'Kunden E-Mail',
            'company_shipments_add_form_carrier_phone' => 'Kunden Telefon',
            
            'company_shipments_add_form_upload_info_title' => 'Standorte werden geladen :',
            'company_shipments_add_form_upload_info_sub_title' => 'Installationsort 1',
            'company_shipments_add_form_upload_info_new_select' => 'new',
            'company_shipments_add_form_upload_info_company_name' => 'Name der Firma',
            'company_shipments_add_form_upload_info_name_and_surname' => 'Vorname Familienname',
            'company_shipments_add_form_upload_info_phone' => 'Telefon',
            'company_shipments_add_form_upload_info_street' => 'Straße',
            'company_shipments_add_form_upload_info_zip_code' => 'Postleitzahl',
            'company_shipments_add_form_upload_info_city' => 'Stadt',
            'company_shipments_add_form_upload_info_country_no' => 'Nein',
            'company_shipments_add_form_upload_info_reference' => 'Referenznummer',
            'company_shipments_add_form_upload_info_details' => '...',
            'company_shipments_add_form_upload_info_button' => 'Installationsort hinzufügen',
            
            'company_shipments_add_form_delivery_info_title' => 'Lieferorte :',
            'company_shipments_add_form_delivery_info_sub_title' => 'Lieferort 1',
            'company_shipments_add_form_delivery_info_new_select' => 'Nein',
            'company_shipments_add_form_delivery_info_company_name' => 'Name der Firma',
            'company_shipments_add_form_delivery_info_name_and_surname' => 'Vorname Familienname',
            'company_shipments_add_form_delivery_info_phone' => 'Telefon',
            'company_shipments_add_form_delivery_info_street' => 'Straße',
            'company_shipments_add_form_delivery_info_zip_code' => 'Postleitzahl',
            'company_shipments_add_form_delivery_info_city' => 'Stadt',
            'company_shipments_add_form_delivery_info_country_no' => 'Nein',
            'company_shipments_add_form_delivery_info_reference' => 'Referenznummer',
            'company_shipments_add_form_delivery_info_details' => '...',
            'company_shipments_add_form_delivery_info_button' => 'Installationsort hinzufügen',
            
            'company_shipments_add_form_price' => 'Gebühr :',
            'company_shipments_add_form_carrier_price' => 'Versand Gebühr :',
            
            'company_shipments_add_form_button_save' => 'Entwurf Erstellen',
            // Shipments Add End
            
            // Shipments Edit Start
            'company_shipments_edit_name' => 'Sendung Erstellen',
            'company_shipments_edit_sub_name' => 'Sendungen',
            'company_shipments_edit_page_title' => 'Sendung Erstellen',
            
            'company_shipments_edit_form_customer_title' => 'Kunden Information :',
            'company_shipments_edit_form_customer_no_select' => 'Nein',
            'company_shipments_edit_form_customer_company_name' => 'Name der Firma',
            'company_shipments_edit_form_customer_name_and_surname' => 'Vorname Familienname',
            'company_shipments_edit_form_customer_street' => 'Straße',
            'company_shipments_edit_form_customer_zip_code' => 'Postleitzahl',
            'company_shipments_edit_form_customer_city' => 'Stadt',
            'company_shipments_edit_form_customer_email' => 'Kunden E-Mail',
            'company_shipments_edit_form_customer_phone' => 'Kunden Telefon',
            'company_shipments_edit_form_customer_reverse_charge' => ' Reverse Charge',
            
            'company_shipments_edit_form_carrier_check' => 'Ich werde den Transport nicht selbst durchführen',
            'company_shipments_edit_form_carrier_title' => 'Transporter:',
            'company_shipments_edit_form_carrier_no_select' => 'Neuer Transporter',
            'company_shipments_edit_form_carrier_company_name' => 'Name der Firma',
            'company_shipments_edit_form_carrier_name_and_surname' => 'Vorname Familienname',
            'company_shipments_edit_form_carrier_street' => 'Straße',
            'company_shipments_edit_form_carrier_zip_code' => 'Postleitzahl',
            'company_shipments_edit_form_carrier_city' => 'Stadt',
            'company_shipments_edit_form_carrier_email' => 'Kunden E-Mail',
            'company_shipments_edit_form_carrier_phone' => 'Kunden Telefon',
            
            'company_shipments_edit_form_upload_info_title' => 'Standorte werden geladen :',
            'company_shipments_edit_form_upload_info_sub_title' => 'Installationsort 1',
            'company_shipments_edit_form_upload_info_select_no' => 'Nein',
            'company_shipments_edit_form_upload_info_company_name' => 'Name der Firma',
            'company_shipments_edit_form_upload_info_name_and_surname' => 'Vorname Familienname',
            'company_shipments_edit_form_upload_info_phone' => 'Telefon',
            'company_shipments_edit_form_upload_info_street' => 'Straße',
            'company_shipments_edit_form_upload_info_zip_code' => 'Postleitzahl',
            'company_shipments_edit_form_upload_info_city' => 'Stadt',
            'company_shipments_edit_form_upload_info_country_no' => 'Nein',
            'company_shipments_edit_form_upload_info_reference' => 'Referenznummer',
            'company_shipments_edit_form_upload_info_details' => '...',
            'company_shipments_edit_form_upload_info_button' => 'Installationsort hinzufügen',
            
            'company_shipments_edit_form_delivery_info_title' => 'Lieferorte :',
            'company_shipments_edit_form_delivery_info_sub_title' => 'Lieferort 1',
            'company_shipments_edit_form_delivery_info_select_no' => 'Nein',
            'company_shipments_edit_form_delivery_info_company_name' => 'Name der Firma',
            'company_shipments_edit_form_delivery_info_name_and_surname' => 'Vorname Familienname',
            'company_shipments_edit_form_delivery_info_phone' => 'Telefon',
            'company_shipments_edit_form_delivery_info_street' => 'Straße',
            'company_shipments_edit_form_delivery_info_zip_code' => 'Postleitzahl',
            'company_shipments_edit_form_delivery_info_city' => 'Stadt',
            'company_shipments_edit_form_delivery_info_country_no' => 'Nein',
            'company_shipments_edit_form_delivery_info_reference' => 'Referenznummer',
            'company_shipments_edit_form_delivery_info_details' => '...',
            'company_shipments_edit_form_delivery_info_button' => 'Installationsort hinzufügen',
            
            'company_shipments_edit_form_price' => 'Gebühr :',
            'company_shipments_edit_form_carrier_price' => 'Versand Gebühr :',
            
            'company_shipments_edit_form_button_save' => 'Sendung aktualisieren',
            // Shipments Edit End
        ];

        // Mevcut tüm çeviri anahtarları için çeviri oluştur
        $translationKeys = TranslationKey::all();
        foreach ($translationKeys as $translationKey) {
            // Çeviriyi oluştur
            Translation::create([
                'language_id' => $language->id,
                'key' => $translationKey->key,
                'value' => $defaultValue[$translationKey->key] ?? '' // Anahtarın değerini al veya boş string ayarla
            ]);
        }
    }
}